[package]
name = "cube_maze"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/cube_maze.rs"

[dependencies]

[dependencies.dir]
path = "../dir"

[dependencies.gfx]
path = "../gfx"

[dependencies.gfx_sizes]
path = "../gfx_sizes"

[dependencies.platform_types]
path = "../platform_types"

[dependencies.qrs]
path = "../qrs"

[dependencies.xs]
path = "../xs"
